import React from 'react';

const Blogs = () => {
    return (
        <div className='container mt-5'>
        <h1>Answer:</h1>
            <p>1. Difference between javascript and node js: <br />JavaScript is a simple programming language that could be run in any browser that supports the JavaScript Engine. On the other hand, Node.js is a running environment or interpreter for the JavaScript programming language. It needs libraries that may be easily accessed from JavaScript programming to make it more useful.For a single web application, JavaScript is typically used for any client-side operation. An operation may be dealing with business validation, dynamic page display at a set time interval. For any web application, these are used for a maximum amount of time. On the other hand, Node.js is generally used for non-blocking accessibility or execution of any operating system. On an operating system, a non-blocking operation involves generating or executing a shell script, retrieving unique hardware-related information in a single call, obtaining installed certificate details in the system, or performing a large number of specified tasks. </p>
            <p>2.Nodejs is a Javascript engine and MongoDB is a database engine.If any project needs a programming environment and a runtime library that offers the basic programming tools or support and can compile or interpret the code. Nodejs is such as tool for the Javascript programming language. There are other similar tools for other languages such as Python, Java, PHP, C#, C++, Go, etc.On the other hand, if any application needs the ability to persistently store data in a way that they can efficiently query or update it later, then they would typically use some form of database. There are dozens of popular databases. MongoDB is one such database. MariaDB, MySql, CouchDB, DynamoDB, Postgres are examples of other databases. Different databases have different strengths and different ways of using them so it's a whole different question to choose the best database for what they're doing. </p>
            <p>3.Difference between sql and NoSQL database: <br />
            SQL meaning Structured query language and NoSQL meaning No declarative query language.SQL databases are primarily called RDBMS or Relational Databases and NoSQL databases are primarily called as Non-relational or distributed database.SQL databases have a predefined schema and NoSQL databases use dynamic schema for unstructured data.SQL databases are not suitable for hierarchical data storage and NoSQL more suitable for the hierarchical data store as it supports key-value pair method.
            SQL meaning Structured query language and NoSQL meaning No declarative query language.SQL databases are primarily called RDBMS or Relational Databases and NoSQL databases are primarily called as Non-relational or distributed database.SQL databases have a predefined schema and NoSQL databases use dynamic schema for unstructured data.SQL databases are not suitable for hierarchical data storage and NoSQL more suitable for the hierarchical data store as it supports key-value pair method.SQL should be used when data validity is super important and NoSQL use when it's more important to have fast data than correct data.
            </p>
            <p>4.JWT meaning JSON Web Token.It is an open standard used to share security information between two parties: a client and a server.JWTs are signed using a cryptographic algorithm to ensure that the claims cannot be altered after the token is issued.Each JWT contains encoded JSON objects, including a set of claims.JWTs differ from other web tokens in that they contain a set of claims. Claims are used to transmit information between two parties. What these claims are depends on the use case at hand. For example, a claim may assert who issued the token, how long it is valid for, or what permissions the client has been granted. </p>
        </div>
    );
};

export default Blogs;